"""Reviewed MCP tool and auxiliary JSON public-model projection declarations."""

from __future__ import annotations

MCP_PROJECTION_SPECS: tuple[dict[str, object], ...] = (
    {
        "model": "notebooklm.types.AccountLimits",
        "mode": "transitive-server-info-account-success-wrapper",
        "keys": ("server", "version", "auth"),
        "optional_keys": ("account",),
        "nested_keys": {
            "auth": (
                "authenticated",
                "storage_exists",
                "json_valid",
                "cookies_present",
                "sid_cookie",
                "profile",
            ),
            "account": (
                "email",
                "authuser",
                "available",
                "notebook_limit",
                "source_limit",
                "tier",
                "output_language",
                "output_language_is_default",
            ),
        },
        "model_contribution_keys": ("notebook_limit", "source_limit", "tier"),
        "evidence": (
            "notebooklm/mcp/tools/meta.py:async def _account_block",
            "notebooklm/mcp/tools/meta.py:async def server_info",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "manual-studio-full-projection",
        "keys": ("id", "title", "type", "status_label", "url"),
        "evidence": ("notebooklm/mcp/tools/_studio_items.py:studio_items",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "manual-studio-compact-projection",
        "keys": ("id", "title", "type", "status_label", "created_at"),
        "evidence": ("notebooklm/mcp/tools/_studio_items.py:compact_studio_item",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "manual-studio-summary-projection",
        "keys": (
            "id",
            "title",
            "type",
            "status_label",
            "url",
            "created_at",
            "generation_prompt",
        ),
        "evidence": ("notebooklm/mcp/tools/_studio_items.py:summarize_studio_item",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "manual-studio-full-list-final-wrapper",
        "keys": ("notebook_id", "items", "total", "offset", "has_more"),
        "nested_union_keys": {
            "items": {
                "note": ("id", "title", "type", "content"),
                "artifact": ("id", "title", "type", "status_label", "url"),
            }
        },
        "evidence": ("notebooklm/mcp/tools/studio.py:async def studio_list",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "manual-studio-compact-list-final-wrapper",
        "keys": ("notebook_id", "items", "total", "offset", "has_more"),
        "nested_keys": {"items": ("id", "title", "type", "status_label", "created_at")},
        "evidence": ('notebooklm/mcp/tools/studio.py:detail == "compact"',),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "manual-studio-summary-list-final-wrapper",
        "keys": ("notebook_id", "items", "total", "offset", "has_more"),
        "nested_union_keys": {
            "items": {
                "note": ("id", "title", "type", "content_preview", "char_count"),
                "artifact": (
                    "id",
                    "title",
                    "type",
                    "status_label",
                    "url",
                    "created_at",
                    "generation_prompt",
                ),
            }
        },
        "evidence": ('notebooklm/mcp/tools/studio.py:detail == "summary"',),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "manual-studio-by-item-final-wrapper",
        "keys": ("notebook_id", "items", "total", "offset", "has_more"),
        "nested_union_keys": {
            "items": {
                "note": ("id", "title", "type", "content"),
                "artifact": (
                    "id",
                    "title",
                    "type",
                    "status_label",
                    "url",
                    "created_at",
                    "generation_prompt",
                ),
            }
        },
        "evidence": ("notebooklm/mcp/tools/studio.py:if item is not None",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-studio-rename-final-projection",
        "keys": (
            "status",
            "notebook_id",
            "item_id",
            "type",
            "new_title",
            "is_mind_map",
        ),
        "evidence": ("notebooklm/mcp/tools/_studio_payloads.py:_artifact_rename_payload",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-studio-delete-confirmation-wrapper",
        "keys": ("status", "preview"),
        "nested_keys": {"preview": ("action", "notebook_id", "item_id", "type", "title")},
        "evidence": ("notebooklm/mcp/tools/studio.py:async def studio_delete",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-studio-delete-final-projection",
        "keys": ("status", "notebook_id", "item_id", "type", "was_note_backed"),
        "evidence": ("notebooklm/mcp/tools/studio.py:was_note_backed",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-resolver-retry-final-projection",
        "keys": ("notebook_id", "artifact_id", "task_id", "status"),
        "evidence": (
            "notebooklm/mcp/_resolve.py:async def resolve_artifact",
            "notebooklm/mcp/tools/studio.py:async def studio_retry",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-selected-artifact-projection",
        "evidence": ("notebooklm/_app/download.py:selected_envelope",),
        "derive": "runtime:artifact-download-selected",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-error-artifact-projection",
        "evidence": ("notebooklm/_app/download.py:artifact=dict(selected)",),
        "derive": "runtime:artifact-download-error",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-dry-all-item-projection",
        "evidence": ("notebooklm/_app/download.py:outcome=DownloadOutcome.ALL_DRY_RUN",),
        "derive": "runtime:artifact-download-dry-all",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-executed-item-projection",
        "evidence": ("notebooklm/_app/download.py:artifacts_results.append",),
        "derive": "runtime:artifact-download-executed",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-mcp-stdio-download-selected-wrapper",
        "evidence": (
            "notebooklm/_app/download.py:class DownloadResult",
            "notebooklm/mcp/tools/studio.py:return {**to_jsonable(result)",
        ),
        "derive": "runtime:artifact-download-mcp-root-selected",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-mcp-stdio-download-error-wrapper",
        "evidence": (
            "notebooklm/_app/download.py:outcome=DownloadOutcome.ERROR",
            "notebooklm/mcp/tools/studio.py:return {**to_jsonable(result)",
        ),
        "derive": "runtime:artifact-download-mcp-root-error",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-mcp-stdio-download-dry-all-wrapper",
        "evidence": (
            "notebooklm/_app/download.py:outcome=DownloadOutcome.ALL_DRY_RUN",
            "notebooklm/mcp/tools/studio.py:return {**to_jsonable(result)",
        ),
        "derive": "runtime:artifact-download-mcp-root-dry-all",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-mcp-stdio-download-executed-wrapper",
        "evidence": (
            "notebooklm/_app/download.py:artifacts_results.append",
            "notebooklm/mcp/tools/studio.py:return {**to_jsonable(result)",
        ),
        "derive": "runtime:artifact-download-mcp-root-executed",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-mcp-remote-download-broker-wrapper",
        "keys": (
            "status",
            "notebook_id",
            "artifact_type",
            "filename",
            "mime_type",
            "size_bytes",
            "url",
            "expires_at",
        ),
        "optional_keys": ("artifact_id",),
        "conditional_key_groups": (
            {
                "condition": "inline textual artifact content",
                "keys": ("content", "char_count", "truncated"),
            },
        ),
        "evidence": (
            "notebooklm/mcp/tools/studio.py:resolved_title",
            "notebooklm/mcp/tools/_studio_download.py:structured: dict[str, Any] =",
        ),
    },
    {
        "model": "notebooklm.types.GenerationStatus",
        "mode": "app-status-view-projection",
        "evidence": (
            "notebooklm/_app/artifacts.py:status_view",
            "notebooklm/mcp/tools/studio.py:studio_status",
        ),
        "derive": "runtime:generation-status-view",
    },
    {
        "model": "notebooklm.types.GenerationStatus",
        "mode": "manual-retry-projection",
        "keys": ("notebook_id", "artifact_id", "task_id", "status"),
        "evidence": ("notebooklm/mcp/tools/studio.py:studio_retry",),
    },
    {
        "model": "notebooklm.types.GenerationStatus",
        "mode": "manual-generate-projection",
        "keys": ("notebook_id", "kind", "task_id", "status", "url", "error"),
        "optional_keys": ("source_ids",),
        "evidence": (
            "notebooklm/_app/generate_retry.py:generation_outcome_from_status",
            "notebooklm/mcp/tools/_studio_payloads.py:_generation_payload",
        ),
    },
    {
        "model": "notebooklm.types.AskResult",
        "mode": "app-view:mcp-final-lite-references",
        "evidence": (
            "notebooklm/_app/views.py:ask_result_view",
            'notebooklm/mcp/tools/chat.py:references == "lite"',
        ),
        "derive": "runtime:ask-result-mcp-lite",
        # ``references`` is deliberately excluded: the tool trims each row
        # to the explicit all-optional ChatReference projection below.
        "nested_fields": ("turn_key", "next_steps"),
    },
    {
        "model": "notebooklm.types.AskResult",
        "mode": "app-view:mcp-final-full-references",
        "evidence": (
            "notebooklm/_app/views.py:ask_result_view",
            "notebooklm/mcp/tools/chat.py:payload.update(ask_payload)",
        ),
        "derive": "runtime:ask-result-mcp-full",
        "nested_fields": ("references", "turn_key", "next_steps"),
    },
    {
        "model": "notebooklm.types.ChatReference",
        "mode": "nested-lite-projection",
        "keys": (),
        "optional_keys": ("source_id", "citation_number", "cited_text"),
        "evidence": ("notebooklm/mcp/tools/chat.py:_LITE_REFERENCE_FIELDS",),
    },
    {
        "model": "notebooklm.types.CitedSourceSelection",
        "mode": "transitive-research-import-final-projection",
        "keys": (
            "status",
            "notebook_id",
            "poll_task_id",
            "task_id",
            "imported",
            "newly_imported",
            "newly_imported_count",
            "already_present",
            "already_present_count",
            "sources_found",
            "sources_selected",
        ),
        "optional_keys": ("cited_only_fallback", "deprecation"),
        "evidence": (
            "notebooklm/mcp/tools/research.py:selection = select_cited_sources",
            "notebooklm/mcp/tools/research.py:result: dict[str, Any] =",
        ),
    },
    {
        "model": "notebooklm.types.MindMap",
        "mode": "transitive-mcp-generation-final-wrapper",
        "evidence": ("notebooklm/mcp/tools/_studio_payloads.py:_generation_payload",),
        "derive": "runtime:mind-map-mcp-final",
    },
    {
        "model": "notebooklm.types.MindMapResult",
        "mode": "transitive-mcp-generation-final-wrapper",
        "evidence": ("notebooklm/mcp/tools/_studio_payloads.py:_generation_payload",),
        "derive": "runtime:mind-map-mcp-final",
    },
    {
        "model": "notebooklm.types.MindMap",
        "mode": "transitive-resolver-rename-final-wrapper",
        "keys": (
            "status",
            "notebook_id",
            "item_id",
            "type",
            "new_title",
            "is_mind_map",
        ),
        "evidence": (
            "notebooklm/_app/artifacts.py:async def rename_artifact",
            "notebooklm/mcp/tools/_studio_payloads.py:_artifact_rename_payload",
        ),
    },
    {
        "model": "notebooklm.types.MindMap",
        "mode": "transitive-resolver-delete-final-wrapper",
        "keys": ("status", "notebook_id", "item_id", "type", "was_note_backed"),
        "evidence": (
            "notebooklm/_app/artifacts.py:async def delete_artifact",
            "notebooklm/mcp/tools/studio.py:was_note_backed = await artifact_core.delete_artifact",
        ),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "manual-studio-full-projection",
        "keys": ("id", "title", "type", "content"),
        "evidence": ("notebooklm/mcp/tools/_studio_items.py:studio_items",),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "manual-studio-compact-projection",
        "keys": ("id", "title", "type", "status_label", "created_at"),
        "evidence": ("notebooklm/mcp/tools/_studio_items.py:compact_studio_item",),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "manual-studio-summary-projection",
        "keys": ("id", "title", "type", "content_preview", "char_count"),
        "evidence": ("notebooklm/mcp/tools/_studio_items.py:summarize_studio_item",),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "manual-studio-full-list-final-wrapper",
        "keys": ("notebook_id", "items", "total", "offset", "has_more"),
        "nested_union_keys": {
            "items": {
                "note": ("id", "title", "type", "content"),
                "artifact": ("id", "title", "type", "status_label", "url"),
            }
        },
        "evidence": ("notebooklm/mcp/tools/studio.py:async def studio_list",),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "manual-studio-compact-list-final-wrapper",
        "keys": ("notebook_id", "items", "total", "offset", "has_more"),
        "nested_keys": {"items": ("id", "title", "type", "status_label", "created_at")},
        "evidence": ('notebooklm/mcp/tools/studio.py:detail == "compact"',),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "manual-studio-summary-list-final-wrapper",
        "keys": ("notebook_id", "items", "total", "offset", "has_more"),
        "nested_union_keys": {
            "items": {
                "note": ("id", "title", "type", "content_preview", "char_count"),
                "artifact": (
                    "id",
                    "title",
                    "type",
                    "status_label",
                    "url",
                    "created_at",
                    "generation_prompt",
                ),
            }
        },
        "evidence": ('notebooklm/mcp/tools/studio.py:detail == "summary"',),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "manual-studio-by-item-final-wrapper",
        "keys": ("notebook_id", "items", "total", "offset", "has_more"),
        "nested_union_keys": {
            "items": {
                "note": ("id", "title", "type", "content"),
                "artifact": (
                    "id",
                    "title",
                    "type",
                    "status_label",
                    "url",
                    "created_at",
                    "generation_prompt",
                ),
            }
        },
        "evidence": ("notebooklm/mcp/tools/studio.py:if item is not None",),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "transitive-studio-rename-final-projection",
        "keys": (
            "status",
            "notebook_id",
            "item_id",
            "type",
            "new_title",
            "is_mind_map",
        ),
        "evidence": ('notebooklm/mcp/tools/studio.py:resolved.type == "note"',),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "transitive-studio-delete-confirmation-wrapper",
        "keys": ("status", "preview"),
        "nested_keys": {"preview": ("action", "notebook_id", "item_id", "type", "title")},
        "evidence": ("notebooklm/mcp/tools/studio.py:async def studio_delete",),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "transitive-studio-delete-final-projection",
        "keys": ("status", "notebook_id", "item_id", "type", "was_note_backed"),
        "evidence": ('notebooklm/mcp/tools/studio.py:resolved.type == "note"',),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "transitive-note-save-create-final-projection",
        "evidence": ('notebooklm/mcp/tools/notes.py:"status": "created"',),
        "derive": "runtime:mcp-note-create",
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "app-view:notebook_view",
        "evidence": (
            "notebooklm/_app/views.py:notebook_view",
            "notebooklm/mcp/tools/notebooks.py:_notebook_view",
        ),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "app-view:notebook-list-final-wrapper",
        "evidence": (
            "notebooklm/mcp/tools/notebooks.py:page, meta = paginate",
            'notebooklm/mcp/tools/notebooks.py:return {"notebooks": page',
        ),
        "derive": "runtime:list-wrapper-mcp-notebook-page",
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "app-view:notebook-create-final",
        "evidence": (
            "notebooklm/_app/views.py:notebook_view",
            'notebooklm/mcp/tools/notebooks.py:record.pop("id")',
        ),
        "derive": "runtime:mcp-notebook-create",
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "always-listed-delete-confirmation-title-wrapper",
        "keys": ("status", "preview"),
        "nested_keys": {"preview": ("action", "notebook_id", "title")},
        "model_contribution_keys": ("title",),
        "evidence": (
            "notebooklm/mcp/tools/notebooks.py:title = title_for_id(await client.notebooks.list()",
            "notebooklm/mcp/tools/notebooks.py:return needs_confirmation",
        ),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "app-view:notebook-metadata-nested",
        "evidence": (
            'notebooklm/mcp/tools/notebooks.py:metadata_block["notebook"] =',
            "notebooklm/mcp/tools/notebooks.py:sources_count",
        ),
        "derive": "runtime:mcp-notebook-metadata-notebook",
    },
    {
        "model": "notebooklm.types.NotebookMetadata",
        "mode": "transitive-notebook-describe-final-with-metadata",
        "evidence": (
            "notebooklm/mcp/tools/notebooks.py:output = to_jsonable(result)",
            "notebooklm/mcp/tools/notebooks.py:metadata_block = to_jsonable",
            'notebooklm/mcp/tools/notebooks.py:output["metadata"] = metadata_block',
        ),
        "derive": "runtime:mcp-notebook-describe-with-metadata",
        "nested_fields": ("sources",),
    },
    {
        "model": "notebooklm.types.NotebookDescription",
        "mode": "nested-notebook-describe-final",
        "evidence": ("notebooklm/mcp/tools/notebooks.py:output = to_jsonable(result)",),
        "derive": "runtime:mcp-notebook-describe",
        "nested_fields": "all",
    },
    {
        "model": "notebooklm.types.PromptSuggestion",
        "mode": "manual-standalone-final-wrapper",
        "evidence": ('notebooklm/mcp/tools/chat.py:payload["suggestions"]',),
        "derive": "runtime:prompt-suggestion-mcp",
    },
    {
        "model": "notebooklm.types.PromptSuggestion",
        "mode": "manual-chat-inline-projection",
        "evidence": ('notebooklm/mcp/tools/chat.py:payload["suggested_prompts"]',),
        "derive": "runtime:prompt-suggestion-mcp-chat-inline",
    },
    {
        "model": "notebooklm.types.PromptSuggestion",
        "mode": "manual-chat-suggestion-only-final-wrapper",
        "keys": ("notebook_id", "suggested_prompts"),
        "optional_keys": ("history", "conversation_id", "source_ids"),
        "nested_keys": {"suggested_prompts": ("title", "prompt")},
        "evidence": (
            "notebooklm/mcp/tools/chat.py:ask_result, suggestions = None, await suggest_coro",
            'notebooklm/mcp/tools/chat.py:payload["suggested_prompts"]',
        ),
    },
    {
        "model": "notebooklm.types.ResearchStart",
        "mode": "manual-start-projection",
        "keys": ("notebook_id", "query", "mode", "poll_task_id"),
        "evidence": ("notebooklm/mcp/tools/research.py:start_fields",),
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "manual-status-projection",
        "keys": (
            "notebook_id",
            "task_id",
            "poll_task_id",
            "kind",
            "status",
            "status_code",
            "termination_reason",
            "discovery_mode",
            "created_at",
            "updated_at",
            "duration_seconds",
            "query",
            "sources",
            "sources_total",
            "sources_returned",
            "sources_offset",
            "summary",
            "report",
            "report_char_count",
            "report_truncated",
        ),
        "optional_keys": ("reason_message", "hint", "cancelled", "deprecation"),
        "evidence": ("notebooklm/mcp/tools/research.py:payload",),
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "transitive-cancel-terminal-final-wrapper",
        "keys": (
            "status",
            "notebook_id",
            "poll_task_id",
            "run_id",
            "cancel_requested",
        ),
        "optional_keys": ("deprecation",),
        "model_contribution_keys": ("status",),
        "evidence": (
            "notebooklm/_app/research.py:status = await client.research.poll",
            'notebooklm/mcp/tools/research.py:if status.status in ("completed", "failed")',
        ),
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "transitive-cancel-nonterminal-final-wrapper",
        "keys": (
            "status",
            "notebook_id",
            "poll_task_id",
            "run_id",
            "cancel_requested",
            "run_status_before",
        ),
        "optional_keys": ("deprecation",),
        "model_contribution_keys": ("status",),
        "evidence": (
            "notebooklm/_app/research.py:status = await client.research.poll",
            'notebooklm/mcp/tools/research.py:"run_status_before": status.status',
        ),
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "transitive-import-final-wrapper",
        "keys": (
            "status",
            "notebook_id",
            "poll_task_id",
            "task_id",
            "imported",
            "newly_imported",
            "newly_imported_count",
            "already_present",
            "already_present_count",
            "sources_found",
            "sources_selected",
        ),
        "optional_keys": ("cited_only_fallback", "deprecation"),
        "nested_keys": {
            "imported": ("id", "title"),
            "newly_imported": ("id", "title"),
            "already_present": ("id", "title", "url"),
        },
        "model_contribution_keys": ("sources",),
        "evidence": (
            "notebooklm/_app/research.py:status = await client.research.poll",
            'notebooklm/mcp/tools/research.py:"sources_found": len(sources)',
        ),
    },
    {
        "model": "notebooklm.types.ResearchSource",
        "mode": "nested-public-dict-report-omitted",
        "evidence": (
            "notebooklm/_app/research.py:src.to_public_dict()",
            "notebooklm/mcp/tools/research.py:to_jsonable(result.sources)",
            'notebooklm/mcp/tools/research.py:del src["report_markdown"]',
        ),
        "derive": "runtime:research-source-public-dict-without-report",
    },
    {
        "model": "notebooklm.types.ResearchSource",
        "mode": "nested-public-dict-report-included-truncated",
        "evidence": (
            "notebooklm/_app/research.py:src.to_public_dict()",
            "notebooklm/mcp/tools/research.py:to_jsonable(result.sources)",
            'notebooklm/mcp/tools/research.py:src["report_markdown"] =',
        ),
        "derive": "runtime:research-source-public-dict",
    },
    {
        "model": "notebooklm.types.ResearchSource",
        "mode": "transitive-import-source-count-contribution",
        "keys": ("sources_found",),
        "contribution_semantics": (
            "ResearchSource list membership contributes only to sources_found; no source "
            "field envelope is serialized on this path"
        ),
        "evidence": (
            "notebooklm/_app/research.py:sources=[src.to_public_dict() for src in status.sources]",
            'notebooklm/mcp/tools/research.py:"sources_found": len(sources)',
        ),
    },
    {
        "model": "notebooklm.types.ShareStatus",
        "mode": "app-view:share_status_view",
        "evidence": (
            "notebooklm/_app/views.py:share_status_view",
            "notebooklm/mcp/tools/sharing.py:_status_payload",
        ),
    },
    {
        "model": "notebooklm.types.ShareStatus",
        "mode": "app-view:share_status_view+view_level",
        "evidence": ("notebooklm/mcp/tools/sharing.py:view_level",),
    },
    {
        "model": "notebooklm.types.ShareStatus",
        "mode": "app-view:mutation-final-updated",
        "keys": (
            "status",
            "notebook_id",
            "is_public",
            "access",
            "share_url",
            "max_individuals_share_limit",
            "is_public_sharing_allowed",
            "is_public_sharing_denied",
            "shared_users",
        ),
        "evidence": ('notebooklm/mcp/tools/sharing.py:return {"status": "updated"',),
    },
    {
        "model": "notebooklm.types.ShareStatus",
        "mode": "app-view:mutation-final-updated+view_level",
        "keys": (
            "status",
            "notebook_id",
            "is_public",
            "access",
            "share_url",
            "max_individuals_share_limit",
            "is_public_sharing_allowed",
            "is_public_sharing_denied",
            "shared_users",
            "view_level",
        ),
        "evidence": (
            'notebooklm/mcp/tools/sharing.py:payload["view_level"]',
            'notebooklm/mcp/tools/sharing.py:return {"status": "updated"',
        ),
    },
    {
        "model": "notebooklm.types.ShareStatus",
        "mode": "conditional-public-widening-confirmation-wrapper",
        "keys": ("status", "preview"),
        "nested_keys": {
            "preview": ("action", "notebook_id", "change"),
        },
        "nested_optional_keys": {"preview": ("view_level",)},
        "model_contribution_keys": ("is_public",),
        "projection_condition": "current ShareStatus.is_public is false",
        "evidence": (
            "notebooklm/mcp/tools/sharing.py:current = await client.sharing.get_status(nb_id)",
            "notebooklm/mcp/tools/sharing.py:if not current.is_public",
            "notebooklm/mcp/tools/sharing.py:return needs_confirmation(preview)",
        ),
    },
    {
        "model": "notebooklm.types.SharedUser",
        "mode": "nested-manual-field-projection",
        "keys": ("email", "permission", "display_name", "avatar_url"),
        "evidence": ("notebooklm/_app/views.py:shared_users",),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "app-view:source_view",
        "evidence": (
            "notebooklm/_app/views.py:source_view",
            "notebooklm/mcp/tools/sources.py:_source_view",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "app-view:source-list-final-wrapper",
        "evidence": (
            "notebooklm/mcp/tools/sources.py:async def source_list",
            "notebooklm/mcp/tools/sources.py:page, meta = paginate",
        ),
        "derive": "runtime:list-wrapper-mcp-source-page",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "manual-compact-list-final-wrapper",
        "evidence": (
            "notebooklm/mcp/tools/sources.py:async def source_list",
            "notebooklm/mcp/tools/sources.py:_source_compact",
            "notebooklm/_app/pagination.py:return page",
        ),
        "derive": {
            "kind": "ast-compact-list-wrapper",
            "path": "notebooklm/mcp/tools/sources.py",
            "function": "source_list",
            "variable": "_COMPACT_SOURCE_FIELDS",
            "meta_path": "notebooklm/_app/pagination.py",
            "meta_function": "paginate",
        },
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "manual-compact-projection",
        "evidence": ("notebooklm/mcp/tools/sources.py:_source_compact",),
        "derive": {
            "kind": "ast-assigned-sequence",
            "path": "notebooklm/mcp/tools/sources.py",
            "variable": "_COMPACT_SOURCE_FIELDS",
        },
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "nested-dataclass-source-rename-result",
        "evidence": (
            "notebooklm/_app/source_mutations.py:class SourceRenameResult",
            "notebooklm/mcp/tools/sources.py:to_jsonable(result)",
        ),
        "derive": "runtime:mcp-source-rename-result",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "app-view:source-add-final-wrapper",
        "evidence": (
            "notebooklm/mcp/tools/sources.py:def _add_result_payload",
            "notebooklm/_app/views.py:source_view",
        ),
        "derive": "runtime:source-view-mcp-add",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "app-view:source-add-drive-final-wrapper",
        "evidence": ("notebooklm/mcp/tools/sources.py:to_jsonable(drive_result)",),
        "derive": "runtime:source-view-mcp-add-drive",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "app-view:source-add-drive-file-final-wrapper",
        "evidence": (
            "notebooklm/mcp/tools/sources_drive.py:payload = to_jsonable(result)",
            'notebooklm/mcp/tools/sources_drive.py:payload["source"] = _source_view',
        ),
        "derive": "runtime:source-view-mcp-add-drive-file",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "app-view:source-read-full-final-wrapper",
        "evidence": (
            'notebooklm/mcp/tools/sources.py:detail == "full"',
            'notebooklm/mcp/tools/sources.py:"source": _source_view(read.source)',
        ),
        "derive": "runtime:source-view-mcp-read-full",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "app-view:source-wait-final-wrapper",
        "evidence": (
            "notebooklm/mcp/tools/_waitagg.py:def _aggregate_wait_outcomes",
            "notebooklm/mcp/tools/sources.py:def _wait_after_add",
        ),
        "derive": "runtime:source-view-mcp-wait",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-batch-added-item-final-wrapper",
        "keys": ("status", "notebook_id", "added", "failed", "results"),
        "nested_keys": {"results": ("input", "status", "source_id", "title", "status_label")},
        "nested_optional_keys": {"results": ("warning",)},
        "evidence": ("notebooklm/mcp/tools/sources.py:async def _add_url_batch",),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-batch-error-item-final-wrapper",
        "keys": ("status", "notebook_id", "added", "failed", "results"),
        "nested_keys": {
            "results": ("input", "status", "error"),
            "results[].error": ("code", "message", "retriable"),
        },
        "nested_optional_keys": {"results[].error": ("unconfirmed", "candidates", "hint")},
        "evidence": (
            "notebooklm/mcp/tools/sources.py:tool_error_payload(exc)",
            "notebooklm/mcp/_errors.py:def tool_error_payload",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-delete-confirmation-final-wrapper",
        "keys": ("status", "preview"),
        "nested_keys": {"preview": ("action", "notebook_id", "source_id", "title")},
        "evidence": (
            "notebooklm/mcp/tools/sources.py:title_for_id",
            "notebooklm/mcp/_confirm.py:def needs_confirmation",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-research-import-new-source-projection",
        "keys": ("id", "title"),
        "evidence": (
            "notebooklm/_research_import.py:def _imported_source_entry",
            "notebooklm/mcp/tools/research.py:newly_imported = to_jsonable(outcome.newly_imported)",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-research-import-existing-source-projection",
        "keys": ("id", "title", "url"),
        "evidence": (
            "notebooklm/_research_import.py:def _partition_requested_sources",
            "notebooklm/mcp/tools/research.py:already_present = to_jsonable(outcome.already_present)",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-remote-upload-await-final-wrapper",
        "adapter_surface": "MCP await_upload tool result",
        "keys": ("status", "source_id", "file"),
        "nested_keys": {"file": ("source_id", "name", "size", "mime", "sha256")},
        "model_contribution_keys": ("id",),
        "evidence": (
            "notebooklm/mcp/_fileroutes.py:source_id = str(result.source.id)",
            'notebooklm/mcp/tools/_fileupload.py:return {"status": "received"',
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-remote-upload-http-final-wrapper",
        "adapter_surface": "MCP auxiliary file-route JSON response",
        "keys": ("status", "source_id"),
        "model_contribution_keys": ("id",),
        "evidence": (
            "notebooklm/mcp/_fileroutes.py:source_id = str(result.source.id)",
            'notebooklm/mcp/_fileroutes.py:{"status": "added", "source_id": source_id}',
        ),
    },
    {
        "model": "notebooklm.types.SourceFulltext",
        "mode": "manual-content-projection",
        "keys": (
            "notebook_id",
            "source_id",
            "source",
            "content",
            "char_count",
            "truncated",
            "output_format",
        ),
        "evidence": ('notebooklm/mcp/tools/sources.py:detail == "full"',),
    },
    {
        "model": "notebooklm.types.SourceGuide",
        "mode": "manual-guide-projection",
        "keys": ("notebook_id", "source_id", "summary", "keywords"),
        "evidence": ('notebooklm/mcp/tools/sources.py:detail == "summary"',),
    },
    {
        "model": "notebooklm.types.UserSettings",
        "mode": "transitive-server-info-account-success-wrapper",
        "keys": ("server", "version", "auth"),
        "optional_keys": ("account",),
        "nested_keys": {
            "auth": (
                "authenticated",
                "storage_exists",
                "json_valid",
                "cookies_present",
                "sid_cookie",
                "profile",
            ),
            "account": (
                "email",
                "authuser",
                "available",
                "notebook_limit",
                "source_limit",
                "tier",
                "output_language",
                "output_language_is_default",
            ),
        },
        "model_contribution_keys": (
            "notebook_limit",
            "source_limit",
            "tier",
            "output_language",
            "output_language_is_default",
        ),
        "evidence": (
            "notebooklm/mcp/tools/meta.py:async def _account_block",
            "notebooklm/mcp/tools/meta.py:async def server_info",
        ),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "conditional-noncanonical-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/mcp/_resolve.py:async def resolve_notebook",
            "notebooklm/mcp/_resolve.py:items = await client.notebooks.list()",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "conditional-noncanonical-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/mcp/_resolve.py:async def resolve_source",
            "notebooklm/mcp/_resolve.py:items = await client.sources.list(notebook_id)",
        ),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "conditional-noncanonical-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/mcp/_resolve.py:async def resolve_note",
            "notebooklm/mcp/_resolve.py:items = await client.notes.list(notebook_id)",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "conditional-noncanonical-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/mcp/_resolve.py:async def resolve_artifact",
            "notebooklm/mcp/_resolve.py:items = await client.artifacts.list(notebook_id)",
        ),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "always-listed-studio-item-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/mcp/tools/_studio_items.py:async def resolve_studio_item",
            "notebooklm/mcp/tools/_studio_items.py:items = await studio_items(client, nb_id",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "always-listed-studio-item-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/mcp/tools/_studio_items.py:async def resolve_studio_item",
            "notebooklm/mcp/tools/_studio_items.py:items = await studio_items(client, nb_id",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "always-listed-studio-download-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/mcp/tools/_studio_download.py:def _resolve_artifact_id",
            "notebooklm/mcp/tools/studio.py:artifact_resolver=_resolve_artifact_id",
        ),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "conditional-resolver-error-text-contribution",
        "keys": ("message",),
        "optional_keys": ("hint",),
        "model_contribution_keys": ("id", "title"),
        "adapter_surface": "MCP ToolError flat message/hint",
        "evidence": (
            "notebooklm/mcp/_resolve.py:async def resolve_notebook",
            "notebooklm/mcp/_resolve.py:def _ambiguous_title_error",
            "notebooklm/mcp/_errors.py:def to_tool_error",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "conditional-resolver-error-text-contribution",
        "keys": ("message",),
        "optional_keys": ("hint",),
        "model_contribution_keys": ("id", "title"),
        "adapter_surface": "MCP ToolError flat message/hint",
        "evidence": (
            "notebooklm/mcp/_resolve.py:async def resolve_source",
            "notebooklm/mcp/_resolve.py:def _ambiguous_title_error",
            "notebooklm/mcp/_errors.py:def to_tool_error",
        ),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "conditional-resolver-error-text-contribution",
        "keys": ("message",),
        "optional_keys": ("hint",),
        "model_contribution_keys": ("id", "title"),
        "adapter_surface": "MCP ToolError flat message/hint",
        "evidence": (
            "notebooklm/mcp/_resolve.py:async def resolve_note",
            "notebooklm/mcp/_resolve.py:def _ambiguous_title_error",
            "notebooklm/mcp/_errors.py:def to_tool_error",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "conditional-resolver-error-text-contribution",
        "keys": ("message",),
        "optional_keys": ("hint",),
        "model_contribution_keys": ("id", "title"),
        "adapter_surface": "MCP ToolError flat message/hint",
        "evidence": (
            "notebooklm/mcp/_resolve.py:async def resolve_artifact",
            "notebooklm/mcp/_resolve.py:def _ambiguous_title_error",
            "notebooklm/mcp/_errors.py:def to_tool_error",
        ),
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "always-listed-resolver-error-text-contribution",
        "keys": ("message",),
        "optional_keys": ("hint",),
        "model_contribution_keys": ("id", "name"),
        "adapter_surface": "MCP ToolError flat message/hint",
        "evidence": (
            "notebooklm/_app/labels.py:async def resolve_label_id",
            "notebooklm/mcp/tools/sources.py:label_resolver=labels_core.resolve_label_id",
            "notebooklm/mcp/_errors.py:def to_tool_error",
        ),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "always-listed-studio-resolver-error-text-contribution",
        "keys": ("message",),
        "optional_keys": ("hint",),
        "model_contribution_keys": ("id", "title"),
        "adapter_surface": "MCP ToolError flat message/hint",
        "evidence": (
            "notebooklm/mcp/tools/_studio_items.py:def _match_studio_ref",
            "notebooklm/mcp/tools/_studio_items.py:async def resolve_studio_item",
            "notebooklm/mcp/_errors.py:def to_tool_error",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "always-listed-studio-resolver-error-text-contribution",
        "keys": ("message",),
        "optional_keys": ("hint",),
        "model_contribution_keys": ("id", "title"),
        "adapter_surface": "MCP ToolError flat message/hint",
        "evidence": (
            "notebooklm/mcp/tools/_studio_items.py:def _match_studio_ref",
            "notebooklm/mcp/tools/_studio_items.py:async def resolve_studio_item",
            "notebooklm/mcp/_errors.py:def to_tool_error",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "always-listed-studio-download-resolver-error-text-contribution",
        "keys": ("message",),
        "optional_keys": ("hint",),
        "model_contribution_keys": ("id", "title"),
        "adapter_surface": "MCP ToolError flat message/hint",
        "evidence": (
            "notebooklm/mcp/tools/_studio_download.py:def _resolve_artifact_id",
            "notebooklm/mcp/tools/studio.py:artifact_resolver=_resolve_artifact_id",
            "notebooklm/mcp/_errors.py:def to_tool_error",
        ),
    },
)

__all__ = ["MCP_PROJECTION_SPECS"]
