"""Reviewed CLI ``--json`` public-model projection declarations."""

from __future__ import annotations

CLI_PROJECTION_SPECS: tuple[dict[str, object], ...] = (
    {
        "model": "notebooklm.types.Artifact",
        "mode": "manual-list-row-projection",
        "keys": (
            "index",
            "id",
            "title",
            "type",
            "type_id",
            "status",
            "status_id",
            "created_at",
        ),
        "evidence": ("notebooklm/cli/artifact_cmd.py:artifact_list",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "manual-list-final-wrapper",
        "keys": ("notebook_id", "notebook_title", "artifacts", "count"),
        "nested_keys": {
            "artifacts": (
                "index",
                "id",
                "title",
                "type",
                "type_id",
                "status",
                "status_id",
                "created_at",
            )
        },
        "evidence": (
            'notebooklm/cli/artifact_cmd.py:items_key="artifacts"',
            "notebooklm/cli/services/listing.py:def prepare_list",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "manual-get-projection",
        "keys": (
            "notebook_id",
            "id",
            "title",
            "type",
            "type_id",
            "status",
            "status_id",
            "created_at",
            "found",
        ),
        "evidence": ("notebooklm/cli/artifact_cmd.py:artifact_get",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-selected-artifact-projection",
        "evidence": ("notebooklm/_app/download.py:selected_envelope",),
        "derive": "runtime:artifact-download-selected",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-error-artifact-projection",
        "evidence": ("notebooklm/_app/download.py:artifact=dict(selected)",),
        "derive": "runtime:artifact-download-error",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-dry-all-item-projection",
        "evidence": ("notebooklm/_app/download.py:outcome=DownloadOutcome.ALL_DRY_RUN",),
        "derive": "runtime:artifact-download-dry-all",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-executed-item-projection",
        "evidence": ("notebooklm/_app/download.py:artifacts_results.append",),
        "derive": "runtime:artifact-download-executed",
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-no-artifacts-final-wrapper",
        "keys": ("error", "suggestion"),
        "evidence": ("notebooklm/cli/services/download.py:DownloadOutcome.NO_ARTIFACTS",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-error-final-wrapper",
        "keys": ("error",),
        "optional_keys": ("artifact", "suggestion"),
        "nested_keys": {"artifact": ("id", "title", "created_at")},
        "evidence": ("notebooklm/cli/services/download.py:DownloadOutcome.ERROR",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-all-dry-run-final-wrapper",
        "keys": ("dry_run", "operation", "count", "output_dir", "artifacts"),
        "nested_keys": {"artifacts": ("id", "title", "filename")},
        "evidence": ("notebooklm/cli/services/download.py:DownloadOutcome.ALL_DRY_RUN",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-all-executed-final-wrapper",
        "keys": (
            "operation",
            "output_dir",
            "total",
            "succeeded_count",
            "failed_count",
            "skipped_count",
            "artifacts",
        ),
        "optional_keys": ("error",),
        "nested_keys": {"artifacts": ("id", "title", "filename", "status")},
        "evidence": ("notebooklm/cli/services/download.py:DownloadOutcome.ALL_EXECUTED",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-single-dry-run-final-wrapper",
        "keys": ("dry_run", "operation", "artifact", "output_path"),
        "nested_keys": {"artifact": ("id", "title", "selection_reason")},
        "evidence": ("notebooklm/cli/services/download.py:DownloadOutcome.SINGLE_DRY_RUN",),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "transitive-download-single-downloaded-final-wrapper",
        "keys": ("operation", "artifact", "output_path", "status"),
        "nested_keys": {"artifact": ("id", "title", "selection_reason")},
        "evidence": ("notebooklm/cli/services/download.py:# SINGLE_DOWNLOADED",),
    },
    {
        "model": "notebooklm.types.GenerationStatus",
        "mode": "manual-poll-projection",
        "keys": ("task_id", "status", "url", "error", "error_code", "metadata"),
        "evidence": ("notebooklm/cli/artifact_cmd.py:artifact_poll",),
    },
    {
        "model": "notebooklm.types.GenerationStatus",
        "mode": "manual-wait-projection",
        "keys": ("artifact_id", "status", "url", "error"),
        "evidence": (
            "notebooklm/cli/artifact_cmd.py:artifact_wait",
            "notebooklm/cli/artifact_cmd.py:artifact_retry",
        ),
    },
    {
        "model": "notebooklm.types.GenerationStatus",
        "mode": "manual-retry-kickoff-projection",
        "keys": ("task_id", "status", "url", "error", "error_code"),
        "evidence": ("notebooklm/cli/artifact_cmd.py:if not wait",),
    },
    {
        "model": "notebooklm.types.GenerationStatus",
        "mode": "manual-generation-completed-projection",
        "keys": ("task_id", "status", "url"),
        "evidence": (
            "notebooklm/_app/generate_retry.py:generation_outcome_from_status",
            "notebooklm/cli/generate_cmd.py:_output_generation_outcome",
        ),
    },
    {
        "model": "notebooklm.types.GenerationStatus",
        "mode": "manual-generation-pending-projection",
        "keys": ("task_id", "status"),
        "evidence": (
            "notebooklm/_app/generate_retry.py:generation_outcome_from_status",
            "notebooklm/cli/generate_cmd.py:_output_generation_outcome",
        ),
    },
    {
        "model": "notebooklm.types.GenerationStatus",
        "mode": "manual-generation-failure-envelope",
        "keys": ("error", "code", "message"),
        "evidence": (
            "notebooklm/_app/generate_retry.py:generation_outcome_from_status",
            "notebooklm/cli/generate_cmd.py:_output_generation_outcome",
            "notebooklm/cli/error_handler.py:response: dict =",
        ),
    },
    {
        "model": "notebooklm.types.GenerationStatus",
        "mode": "nested-timeout-transition-projection",
        "keys": ("task_id", "status", "url", "error", "error_code", "metadata"),
        "evidence": ("notebooklm/cli/error_handler.py:_generation_status_extra",),
    },
    {
        "model": "notebooklm.types.AskResult",
        "mode": "app-view:cli-final-with-note-outcome",
        "evidence": (
            "notebooklm/_app/views.py:ask_result_view",
            "notebooklm/cli/chat_cmd.py:data = ask_result_view",
        ),
        "derive": "runtime:ask-result-cli-final",
        "nested_fields": ("references", "turn_key", "next_steps"),
    },
    {
        "model": "notebooklm.types.CitedSourceSelection",
        "mode": "manual-completed-wait-projection",
        "keys": ("cited_only", "cited_sources_selected", "cited_only_fallback"),
        "evidence": ("notebooklm/cli/research_cmd.py:_completed_wait_payload",),
    },
    {
        "model": "notebooklm.types.CitedSourceSelection",
        "mode": "manual-direct-import-projection",
        "keys": ("cited_only", "cited_only_fallback"),
        "evidence": ("notebooklm/cli/research_cmd.py:_render_import_result",),
    },
    {
        "model": "notebooklm.types.CitedSourceSelection",
        "mode": "transitive-source-add-research-completed-projection",
        "keys": ("status", "task_id", "sources_found", "sources", "report"),
        "optional_keys": (
            "cited_only",
            "cited_sources_selected",
            "cited_only_fallback",
            "imported",
            "imported_sources",
        ),
        "evidence": (
            "notebooklm/_app/source_research.py:def cited_selection",
            "notebooklm/cli/_source_render.py:completed_payload",
        ),
    },
    {
        "model": "notebooklm.types.Collection",
        "mode": "manual-mutation-projection",
        "evidence": ("notebooklm/cli/collection_cmd.py:_collection_payload",),
        "derive": "runtime:cli-collection-mutation",
    },
    {
        "model": "notebooklm.types.Collection",
        "mode": "manual-add-membership-final-projection",
        "evidence": ("notebooklm/cli/collection_cmd.py:added_notebook_ids",),
        "derive": "runtime:cli-collection-add",
    },
    {
        "model": "notebooklm.types.Collection",
        "mode": "manual-remove-membership-final-projection",
        "evidence": ("notebooklm/cli/collection_cmd.py:removed_notebook_ids",),
        "derive": "runtime:cli-collection-remove",
    },
    {
        "model": "notebooklm.types.Collection",
        "mode": "manual-list-row-projection",
        "keys": ("index", "id", "name", "emoji", "notebook_count"),
        "evidence": ("notebooklm/cli/collection_cmd.py:collection_list",),
    },
    {
        "model": "notebooklm.types.Collection",
        "mode": "manual-list-final-wrapper",
        "keys": ("collections", "count"),
        "nested_keys": {"collections": ("index", "id", "name", "emoji", "notebook_count")},
        "evidence": (
            'notebooklm/cli/collection_cmd.py:items_key="collections"',
            "notebooklm/cli/services/listing.py:def prepare_list",
        ),
    },
    {
        "model": "notebooklm.types.Collection",
        "mode": "resolver-ambiguous-id-error-wrapper",
        "keys": ("error", "code", "message", "id", "candidates"),
        "nested_keys": {"candidates": ("id", "emoji", "notebook_count")},
        "model_contribution_keys": ("id", "emoji", "notebook_ids"),
        "evidence": (
            "notebooklm/_app/collections.py:_candidate_payload(prefix_matches)",
            "notebooklm/cli/collection_cmd.py:def _handle_collection_resolution_error",
        ),
    },
    {
        "model": "notebooklm.types.Collection",
        "mode": "resolver-ambiguous-name-error-wrapper",
        "keys": ("error", "code", "message", "name", "candidates"),
        "nested_keys": {"candidates": ("id", "emoji", "notebook_count")},
        "model_contribution_keys": ("id", "emoji", "notebook_ids"),
        "evidence": (
            "notebooklm/_app/collections.py:_candidate_payload(name_matches)",
            "notebooklm/cli/collection_cmd.py:def _handle_collection_resolution_error",
        ),
    },
    {
        "model": "notebooklm.types.Collection",
        "mode": "resolver-near-miss-error-wrapper",
        "keys": ("error", "code", "message", "id", "candidates"),
        "nested_keys": {"candidates": ("id", "title")},
        "model_contribution_keys": ("id", "name"),
        "evidence": (
            "notebooklm/_app/collections.py:candidates = near_miss_candidates",
            "notebooklm/cli/collection_cmd.py:def _handle_collection_resolution_error",
        ),
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "manual-list-projection",
        "evidence": ("notebooklm/cli/services/label_listing.py:_label_serialize",),
        "derive": "runtime:cli-label-list",
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "manual-list-final-wrapper",
        "keys": ("labels", "count"),
        "nested_keys": {
            "labels": ("id", "name", "emoji", "source_ids", "sources"),
            "labels[].sources": ("id", "title"),
        },
        "evidence": (
            "notebooklm/cli/services/label_listing.py:async def execute_label_list",
            "notebooklm/cli/services/listing.py:envelope =",
        ),
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "resolver-ambiguous-id-error-wrapper",
        "keys": ("error", "code", "message", "id", "candidates"),
        "nested_keys": {"candidates": ("id", "emoji", "source_count")},
        "model_contribution_keys": ("id", "emoji", "source_ids"),
        "evidence": (
            "notebooklm/_app/labels.py:_candidate_payload(prefix_matches)",
            "notebooklm/cli/label_cmd.py:def _handle_label_resolution_error",
        ),
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "resolver-ambiguous-name-error-wrapper",
        "keys": ("error", "code", "message", "name", "candidates"),
        "nested_keys": {"candidates": ("id", "emoji", "source_count")},
        "model_contribution_keys": ("id", "emoji", "source_ids"),
        "evidence": (
            "notebooklm/_app/labels.py:_candidate_payload(name_matches)",
            "notebooklm/cli/label_cmd.py:def _handle_label_resolution_error",
        ),
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "resolver-near-miss-error-wrapper",
        "keys": ("error", "code", "message", "id", "notebook_id", "candidates"),
        "nested_keys": {"candidates": ("id", "title")},
        "model_contribution_keys": ("id", "name"),
        "evidence": (
            "notebooklm/_app/labels.py:candidates = near_miss_candidates",
            "notebooklm/cli/label_cmd.py:def _handle_label_resolution_error",
        ),
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "manual-mutation-projection",
        "evidence": ("notebooklm/cli/label_cmd.py:_label_payload",),
        "derive": "runtime:cli-label-payload",
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "manual-create-rename-emoji-final-projection",
        "evidence": (
            "notebooklm/cli/label_cmd.py:label_create",
            "notebooklm/cli/label_cmd.py:label_rename",
            "notebooklm/cli/label_cmd.py:label_emoji",
        ),
        "derive": "runtime:cli-label-final-command",
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "manual-generate-final-projection",
        "evidence": ("notebooklm/cli/label_cmd.py:label_generate",),
        "derive": "runtime:cli-label-final-generate",
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "manual-add-final-projection",
        "evidence": ("notebooklm/cli/label_cmd.py:label_add",),
        "derive": "runtime:cli-label-final-add",
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "manual-remove-final-projection",
        "evidence": ("notebooklm/cli/label_cmd.py:label_remove",),
        "derive": "runtime:cli-label-final-remove",
    },
    {
        "model": "notebooklm.types.MindMap",
        "mode": "transitive-cli-final-tree-wrapper",
        "evidence": ("notebooklm/cli/generate_cmd.py:_output_mind_map_result",),
        "derive": "runtime:mind-map-cli-final",
    },
    {
        "model": "notebooklm.types.MindMapResult",
        "mode": "transitive-cli-final-tree-wrapper",
        "evidence": ("notebooklm/cli/generate_cmd.py:_output_mind_map_result",),
        "derive": "runtime:mind-map-cli-final",
    },
    {
        "model": "notebooklm.types.MindMap",
        "mode": "transitive-artifact-delete-final-carveout",
        "keys": ("id", "deleted"),
        "conditional_key_groups": (
            {"condition": "note-backed mind map", "keys": ("kind", "note")},
        ),
        "evidence": (
            "notebooklm/_app/artifacts.py:async def delete_artifact",
            "notebooklm/cli/artifact_cmd.py:def serialize_success",
        ),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "manual-list-row-projection",
        "keys": ("id", "title", "preview"),
        "evidence": ("notebooklm/cli/note_cmd.py:note_list",),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "manual-list-final-wrapper",
        "keys": ("notebook_id", "notes", "count"),
        "nested_keys": {"notes": ("id", "title", "preview")},
        "evidence": (
            "notebooklm/cli/note_cmd.py:def note_list",
            "notebooklm/cli/services/listing.py:envelope =",
        ),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "dataclass-get-projection",
        "keys": ("id", "notebook_id", "title", "content", "created_at", "found"),
        "evidence": ("notebooklm/cli/note_cmd.py:payload = asdict",),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "manual-create-projection",
        "keys": ("id", "notebook_id", "title", "created"),
        "evidence": ("notebooklm/cli/note_cmd.py:note_create",),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "transitive-chat-save-note-projection",
        "evidence": (
            'notebooklm/_app/chat.py:note={"id": note.id, "title": note.title}',
            'notebooklm/cli/chat_cmd.py:data["note"] = note_save_result',
        ),
        "derive": "runtime:cli-note-chat-save",
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "transitive-history-save-note-final-wrapper",
        "evidence": (
            "notebooklm/cli/chat_cmd.py:def _history_json_payload",
            'notebooklm/cli/chat_cmd.py:"note": {"id": note.id',
        ),
        "derive": "runtime:cli-note-history-save",
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "manual-list-row-projection",
        "keys": (
            "index",
            "id",
            "title",
            "is_owner",
            "role",
            "created_at",
            "last_viewed_at",
            "modified_at",
        ),
        "evidence": ("notebooklm/cli/notebook_cmd.py:notebook_viewed_keys",),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "manual-list-final-wrapper",
        "keys": ("notebooks", "count"),
        "nested_keys": {
            "notebooks": (
                "index",
                "id",
                "title",
                "is_owner",
                "role",
                "created_at",
                "last_viewed_at",
                "modified_at",
            )
        },
        "evidence": (
            'notebooklm/cli/notebook_cmd.py:items_key="notebooks"',
            "notebooklm/cli/services/listing.py:def prepare_list",
        ),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "manual-session-use-projection",
        "evidence": ("notebooklm/cli/session_cmd.py:use_notebook",),
        "derive": {
            "kind": "ast-dict",
            "path": "notebooklm/cli/session_cmd.py",
            "function": "use_notebook",
            "contains": ("notebook",),
            "nested": ("notebook",),
            "nested_spreads": {"notebook": "notebook-viewed-keys"},
        },
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "manual-create-projection",
        "keys": ("notebook",),
        "nested_keys": {
            "notebook": (
                "id",
                "title",
                "role",
                "created_at",
                "last_viewed_at",
                "modified_at",
            )
        },
        "evidence": ("notebooklm/cli/notebook_cmd.py:create_cmd",),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "manual-create-and-use-projection",
        "keys": ("notebook", "active_notebook_id"),
        "nested_keys": {
            "notebook": (
                "id",
                "title",
                "role",
                "created_at",
                "last_viewed_at",
                "modified_at",
            )
        },
        "evidence": ("notebooklm/cli/notebook_cmd.py:active_notebook_id",),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "manual-collection-member-projection",
        "keys": ("id", "title"),
        "evidence": ("notebooklm/cli/collection_cmd.py:collection_notebooks",),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "transitive-metadata-flattened-projection",
        "evidence": (
            "notebooklm/_types/notebooks.py:class NotebookMetadata",
            "notebooklm/cli/notebook_cmd.py:metadata.to_dict",
        ),
        "derive": "runtime:cli-notebook-metadata-flattened",
    },
    {
        "model": "notebooklm.types.NotebookMetadata",
        "mode": "manual-to-dict-projection",
        "evidence": ("notebooklm/cli/notebook_cmd.py:metadata.to_dict",),
        "derive": "runtime:cli-notebook-metadata-root",
    },
    {
        "model": "notebooklm.types.NotebookDescription",
        "mode": "manual-summary-projection",
        "keys": ("notebook_id", "summary"),
        "evidence": ("notebooklm/cli/notebook_cmd.py:summary_cmd",),
    },
    {
        "model": "notebooklm.types.NotebookDescription",
        "mode": "manual-summary-with-topics-projection",
        "keys": ("notebook_id", "summary", "suggested_topics"),
        "evidence": ("notebooklm/cli/notebook_cmd.py:suggested_topics",),
    },
    {
        "model": "notebooklm.types.PromptSuggestion",
        "mode": "manual-cli-final-wrapper",
        "evidence": ("notebooklm/cli/chat_cmd.py:suggestions = await",),
        "derive": "runtime:prompt-suggestion-cli",
    },
    {
        "model": "notebooklm.types.ReportSuggestion",
        "mode": "manual-field-projection",
        "keys": ("title", "description", "prompt"),
        "evidence": ("notebooklm/cli/artifact_cmd.py:artifact_suggestions",),
    },
    {
        "model": "notebooklm.types.ResearchStart",
        "mode": "transitive-source-add-research-no-wait-projection",
        "evidence": (
            "notebooklm/_app/source_research.py:start_task_id = result.task_id",
            "notebooklm/cli/_source_render.py:payload: dict[str, Any] =",
        ),
        "derive": {
            "kind": "ast-mapping-variable",
            "path": "notebooklm/cli/_source_render.py",
            "function": "_render_add_research_result",
            "variable": "payload",
            "contains": ("task_id",),
        },
    },
    {
        "model": "notebooklm.types.ResearchStart",
        "mode": "transitive-source-add-research-completed-projection",
        "evidence": (
            "notebooklm/_app/source_research.py:start_task_id = result.task_id",
            "notebooklm/cli/_source_render.py:completed_payload: dict[str, Any] =",
        ),
        "derive": {
            "kind": "ast-mapping-variable",
            "path": "notebooklm/cli/_source_render.py",
            "function": "_render_add_research_result",
            "variable": "completed_payload",
            "contains": ("sources_found",),
        },
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "manual-empty-status-projection",
        "evidence": ("notebooklm/cli/research_cmd.py:result.public_dict",),
        "derive": "runtime:research-task-public-dict-empty",
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "manual-status-projection",
        "evidence": ("notebooklm/cli/research_cmd.py:result.public_dict",),
        "derive": "runtime:research-task-public-dict",
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "transitive-wait-completed-final-projection",
        "keys": ("status", "query", "sources_found", "sources", "report"),
        "optional_keys": (
            "cited_only",
            "cited_sources_selected",
            "cited_only_fallback",
            "imported",
            "imported_sources",
        ),
        "nested_keys": {"imported_sources": ("id", "title")},
        "evidence": ("notebooklm/cli/research_cmd.py:_completed_wait_payload",),
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "transitive-wait-failed-final-projection",
        "keys": ("status", "error"),
        "optional_keys": (
            "query",
            "sources",
            "sources_found",
            "report",
            "reason_message",
            "hint",
        ),
        "evidence": ("notebooklm/cli/research_cmd.py:failed_payload",),
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "transitive-wait-no-research-branch-contribution",
        "keys": ("status", "error"),
        "model_contribution_keys": ("status",),
        "projection_condition": "ResearchTask.status selects the no_research branch",
        "contribution_semantics": (
            "The public status selects this fixed error envelope; the timeout branch has no "
            "ResearchTask instance and is intentionally excluded"
        ),
        "evidence": (
            'notebooklm/_app/research.py:if status_val == "no_research"',
            'notebooklm/cli/research_cmd.py:if result.outcome == "no_research"',
        ),
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "transitive-source-add-research-completed-final-projection",
        "keys": ("status", "task_id", "sources_found", "sources", "report"),
        "optional_keys": (
            "cited_only",
            "cited_sources_selected",
            "cited_only_fallback",
            "imported",
            "imported_sources",
        ),
        "nested_keys": {"imported_sources": ("id", "title")},
        "evidence": (
            "notebooklm/_app/source_research.py:sources = [src.to_public_dict()",
            "notebooklm/cli/_source_render.py:completed_payload",
        ),
    },
    {
        "model": "notebooklm.types.ResearchTask",
        "mode": "transitive-source-add-research-failure-final-projection",
        "keys": ("status", "error"),
        "optional_keys": ("reason_message", "hint", "raw_status"),
        "evidence": (
            "notebooklm/_app/source_research.py:status_val = status.status.value",
            "notebooklm/cli/_source_render.py:_exit_with_add_research_status",
        ),
    },
    {
        "model": "notebooklm.types.ResearchSource",
        "mode": "nested-to-public-dict-projection",
        "evidence": ("notebooklm/_types/research.py:to_public_dict",),
        "derive": "runtime:research-source-public-dict",
    },
    {
        "model": "notebooklm.types.ShareStatus",
        "mode": "manual-status-projection",
        "keys": (
            "notebook_id",
            "is_public",
            "access",
            "view_level",
            "share_url",
            "max_individuals_share_limit",
            "is_public_sharing_allowed",
            "is_public_sharing_denied",
            "shared_users",
        ),
        "evidence": ("notebooklm/cli/share_cmd.py:share_status",),
    },
    {
        "model": "notebooklm.types.ShareStatus",
        "mode": "manual-public-projection",
        "keys": ("notebook_id", "is_public", "share_url"),
        "evidence": ("notebooklm/cli/share_cmd.py:share_public",),
    },
    {
        "model": "notebooklm.types.ShareStatus",
        "mode": "manual-view-level-projection",
        "keys": ("notebook_id", "view_level"),
        "evidence": ("notebooklm/cli/share_cmd.py:share_view_level",),
    },
    {
        "model": "notebooklm.types.SharedUser",
        "mode": "nested-manual-field-projection",
        "keys": ("email", "permission", "display_name"),
        "evidence": ("notebooklm/cli/share_cmd.py:shared_users",),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "manual-summary-projection",
        "evidence": ("notebooklm/cli/services/source_serializers.py:source_summary_payload",),
        "derive": "runtime:cli-source-summary",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "manual-row-projection",
        "evidence": ("notebooklm/cli/services/source_serializers.py:source_row_payload",),
        "derive": "runtime:cli-source-row",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "manual-list-final-wrapper",
        "evidence": (
            'notebooklm/cli/services/source_listing.py:items_key="sources"',
            "notebooklm/cli/services/listing.py:def prepare_list",
        ),
        "derive": "runtime:cli-source-final-list",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "manual-get-final-wrapper",
        "evidence": ("notebooklm/cli/_source_render.py:_render_source_get_result",),
        "derive": "runtime:cli-source-final-get",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-add-final-wrapper",
        "evidence": ("notebooklm/cli/_source_render.py:source_add_payload",),
        "derive": "runtime:cli-source-final-add",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-add-drive-final-wrapper",
        "evidence": ("notebooklm/cli/_source_render.py:_render_source_add_drive_result",),
        "derive": "runtime:cli-source-final-add-drive",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-add-drive-file-final-wrapper",
        "evidence": ("notebooklm/cli/_source_render.py:_render_source_add_drive_file_result",),
        "derive": "runtime:cli-source-final-add-drive-file",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "nested-label-list-title-join-projection",
        "evidence": ("notebooklm/cli/services/label_listing.py:_label_serialize",),
        "derive": "runtime:cli-label-title-join",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "nested-label-sources-projection",
        "evidence": ("notebooklm/cli/label_cmd.py:label_sources",),
        "derive": {
            "kind": "ast-dict",
            "path": "notebooklm/cli/label_cmd.py",
            "function": "label_sources",
            "contains": ("url",),
        },
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-wait-ready-projection",
        "evidence": ("notebooklm/cli/_source_render.py:SourceWaitReady",),
        "derive": {
            "kind": "ast-dict",
            "path": "notebooklm/cli/_source_render.py",
            "function": "_render_source_wait_outcome",
            "contains": ("title", "status_code"),
        },
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-wait-processing-error-final-wrapper",
        "keys": ("source_id", "status", "status_code", "error"),
        "model_contribution_keys": ("status",),
        "projection_condition": "Source.status is a terminal processing error",
        "contribution_semantics": (
            "Source.status is preserved through SourceProcessingError.status and emitted as "
            "status_code"
        ),
        "evidence": (
            "notebooklm/_source/polling.py:SourceProcessingError(source_id, source.status)",
            "notebooklm/cli/_source_render.py:SourceWaitProcessingError",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-wait-timeout-final-wrapper",
        "keys": (
            "source_id",
            "status",
            "last_status_code",
            "timeout_seconds",
            "error",
        ),
        "model_contribution_keys": ("status",),
        "projection_condition": "polling expires after observing a Source.status",
        "contribution_semantics": (
            "The last public Source.status is preserved through SourceTimeoutError.last_status "
            "and emitted as last_status_code"
        ),
        "evidence": (
            "notebooklm/_source/polling.py:last_status = source.status",
            "notebooklm/cli/_source_render.py:SourceWaitTimeout",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-rename-projection",
        "evidence": ("notebooklm/cli/_source_render.py:_source_rename_payload",),
        "derive": "runtime:cli-source-rename",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-delete-by-title-projection",
        "evidence": (
            "notebooklm/_app/source_mutations.py:execute_source_delete_by_title",
            "notebooklm/cli/_source_render.py:_source_delete_by_title_payload",
        ),
        "derive": "runtime:cli-source-delete-by-title",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-delete-resolver-error-text-wrapper",
        "keys": ("error", "code", "message"),
        "model_contribution_keys": ("id", "title"),
        "projection_condition": (
            "partial-id ambiguity, title collision, or exact-title ambiguity after listing Sources"
        ),
        "adapter_surface": "CLI --json standard error envelope",
        "evidence": (
            "notebooklm/_app/source_mutations.py:build_id_ambiguity_error(source_id, matches)",
            "notebooklm/_app/source_mutations.py:async def resolve_source_by_exact_title",
            "notebooklm/cli/_source_render.py:def _handle_source_mutation_error",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-delete-confirm-by-id-error-wrapper",
        "keys": ("error", "code", "message", "action", "source_id", "notebook_id"),
        "conditional_key_groups": (
            {
                "condition": "partial-id expansion differs from the requested source id",
                "keys": ("status_message",),
            },
        ),
        "model_contribution_keys": ("id", "title"),
        "contribution_semantics": (
            "Source.id always contributes to source_id; Source.title contributes only to the "
            "conditional status_message for a prefix expansion"
        ),
        "projection_condition": "noncanonical source-id resolution followed by JSON confirmation",
        "evidence": (
            "notebooklm/_app/source_mutations.py:resolution = await resolve_source_for_delete",
            "notebooklm/_app/source_mutations.py:status_message=resolution.status_message",
            "notebooklm/cli/_source_render.py:def _handle_source_mutation_error",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-delete-confirm-by-title-error-wrapper",
        "keys": (
            "error",
            "code",
            "message",
            "action",
            "source_id",
            "title",
            "notebook_id",
        ),
        "model_contribution_keys": ("id", "title"),
        "projection_condition": "exact-title Source match followed by JSON confirmation",
        "evidence": (
            "notebooklm/_app/source_mutations.py:source = await resolve_source_by_exact_title",
            'notebooklm/_app/source_mutations.py:action="delete-by-title"',
            "notebooklm/cli/_source_render.py:def _handle_source_mutation_error",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-clean-candidate-projection",
        "evidence": ("notebooklm/_app/source_clean.py:candidates_payload",),
        "derive": "runtime:cli-source-clean-candidate",
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-clean-success-final-wrapper",
        "nested_keys": {
            "candidates": ("id", "title", "status", "reason"),
            "failures": ("id", "error"),
        },
        "evidence": (
            "notebooklm/cli/source_cmd.py:def _dispatch_source_clean_result",
            "notebooklm/cli/source_cmd.py:payload: dict[str, Any] =",
        ),
        "derive": {
            "kind": "ast-mapping-variable",
            "path": "notebooklm/cli/source_cmd.py",
            "function": "_dispatch_source_clean_result",
            "variable": "payload",
            "contains": ("action", "candidates", "deleted_count"),
        },
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-clean-confirm-required-error-wrapper",
        "keys": (
            "error",
            "code",
            "message",
            "action",
            "notebook_id",
            "candidate_count",
            "candidates",
        ),
        "nested_keys": {"candidates": ("id", "title", "status", "reason")},
        "evidence": (
            "notebooklm/cli/source_cmd.py:require_yes_in_json",
            "notebooklm/cli/_source_render.py:def _handle_source_mutation_error",
            "notebooklm/cli/error_handler.py:response: dict =",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-research-import-new-source-projection",
        "keys": ("id", "title"),
        "evidence": (
            "notebooklm/_research_import.py:def _imported_source_entry",
            "notebooklm/cli/research_cmd.py:imported_sources",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-research-import-existing-source-projection",
        "keys": ("id", "title", "url"),
        "evidence": (
            "notebooklm/_research_import.py:def _partition_requested_sources",
            "notebooklm/cli/research_cmd.py:already_present_sources",
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-research-import-direct-final-wrapper",
        "keys": (
            "status",
            "run_id",
            "sources_found",
            "sources_selected",
            "imported",
            "imported_sources",
            "already_present",
            "already_present_sources",
        ),
        "optional_keys": ("cited_only", "cited_only_fallback"),
        "nested_keys": {
            "imported_sources": ("id", "title"),
            "already_present_sources": ("id", "title", "url"),
        },
        "evidence": ("notebooklm/cli/research_cmd.py:def _render_import_result",),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-research-wait-imported-sources-final-wrapper",
        "keys": ("status", "query", "sources_found", "sources", "report"),
        "optional_keys": (
            "cited_only",
            "cited_sources_selected",
            "cited_only_fallback",
            "imported",
            "imported_sources",
        ),
        "nested_keys": {"imported_sources": ("id", "title")},
        "evidence": ("notebooklm/cli/research_cmd.py:def _completed_wait_payload",),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "transitive-source-add-research-imported-sources-final-wrapper",
        "keys": ("status", "task_id", "sources_found", "sources", "report"),
        "optional_keys": (
            "cited_only",
            "cited_sources_selected",
            "cited_only_fallback",
            "imported",
            "imported_sources",
        ),
        "nested_keys": {"imported_sources": ("id", "title")},
        "evidence": (
            "notebooklm/cli/_source_render.py:completed_payload: dict[str, Any] =",
            'notebooklm/cli/_source_render.py:completed_payload["imported_sources"]',
        ),
    },
    {
        "model": "notebooklm.types.SourceFulltext",
        "mode": "manual-field-projection",
        "keys": ("source_id", "title", "kind", "content", "url", "char_count"),
        "evidence": ("notebooklm/cli/services/source_serializers.py:source_fulltext_payload",),
    },
    {
        "model": "notebooklm.types.SourceFulltext",
        "mode": "manual-file-output-projection",
        "keys": ("path", "bytes", "source_id", "title", "kind"),
        "evidence": ("notebooklm/cli/_source_render.py:content_bytes",),
    },
    {
        "model": "notebooklm.types.SourceGuide",
        "mode": "manual-guide-projection",
        "keys": ("source_id", "summary", "keywords"),
        "evidence": ("notebooklm/cli/_source_render.py:_render_source_guide_result",),
    },
    {
        "model": "notebooklm.types.SourceSummary",
        "mode": "nested-manual-to-dict-projection",
        "evidence": ("notebooklm/_types/notebooks.py:class SourceSummary",),
        "derive": "runtime:cli-notebook-metadata-source",
    },
    {
        "model": "notebooklm.types.SuggestedTopic",
        "mode": "nested-scalar-field-projection",
        "keys": ("question",),
        "evidence": ("notebooklm/cli/notebook_cmd.py:topic.question",),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "conditional-noncanonical-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/cli/resolve.py:async def resolve_notebook_id",
            "notebooklm/cli/resolve.py:list_fn=lambda: client.notebooks.list()",
        ),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "always-listed-collection-membership-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/cli/collection_cmd.py:async def _resolve_notebook_ids",
            "notebooklm/cli/collection_cmd.py:notebooks = await client.notebooks.list()",
            'notebooklm/cli/collection_cmd.py:"added_notebook_ids": membership.notebook_ids',
            'notebooklm/cli/collection_cmd.py:"removed_notebook_ids": membership.notebook_ids',
        ),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "artifact-list-title-contribution",
        "keys": ("title",),
        "evidence": (
            "notebooklm/cli/artifact_cmd.py:nb = await client.notebooks.get(notebook_id)",
            'notebooklm/cli/artifact_cmd.py:"notebook_title": nb.title if nb else None',
        ),
    },
    {
        "model": "notebooklm.types.Notebook",
        "mode": "source-list-title-contribution",
        "keys": ("title",),
        "evidence": (
            "notebooklm/cli/services/source_listing.py:nb = await client.notebooks.get(notebook_id)",
            'notebooklm/cli/services/source_listing.py:"notebook_title": nb.title if nb else None',
        ),
    },
    {
        "model": "notebooklm.types.Source",
        "mode": "conditional-noncanonical-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/cli/resolve.py:async def resolve_source_id",
            "notebooklm/cli/resolve.py:list_fn=lambda: client.sources.list(notebook_id)",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "conditional-noncanonical-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/cli/resolve.py:async def resolve_artifact_id",
            "notebooklm/cli/resolve.py:list_fn=lambda: client.artifacts.list(notebook_id)",
        ),
    },
    {
        "model": "notebooklm.types.Artifact",
        "mode": "always-listed-download-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/cli/download_helpers.py:def resolve_partial_artifact_id",
            "notebooklm/cli/services/download.py:artifact_resolver=resolve_partial_artifact_id",
        ),
    },
    {
        "model": "notebooklm.types.Note",
        "mode": "conditional-noncanonical-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/cli/resolve.py:async def resolve_note_id",
            "notebooklm/cli/resolve.py:list_fn=lambda: client.notes.list(notebook_id)",
        ),
    },
    {
        "model": "notebooklm.types.Collection",
        "mode": "always-listed-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/_app/collections.py:async def resolve_collection_id",
            "notebooklm/_app/collections.py:collections = await client.collections.list()",
        ),
    },
    {
        "model": "notebooklm.types.Label",
        "mode": "always-listed-resolver-id-contribution",
        "keys": ("id",),
        "evidence": (
            "notebooklm/_app/labels.py:async def resolve_label_id",
            "notebooklm/_app/labels.py:labels = await client.labels.list(notebook_id)",
        ),
    },
)

__all__ = ["CLI_PROJECTION_SPECS"]
